export const myProjectsData = [
    {
        category: "Pet Project",
        name: "Todo App",
        url: "https://trunghieu99tt.github.io/Todo-List-With-ReactJS/",
        image: require("../../static/images/todo-min.PNG"),
        description: "",
        tags: ["html", "css", "responsive", "reactjs"],
    },
    {
        category: "Real Project",
        dataFilter: "real-project",
        name: "Clothing Shop",
        url: "https://trunghieu99tt.github.io/Clothing-Shop/",
        image: require("../../static/images/clothing-shop-min.PNG"),
        description: "",
        tags: ["html", "css", "responsive", "reactjs"],
    },

    {
        category: "Pet Project",
        dataFilter: "pet-project",
        name: "Christmas",
        url: "https://trunghieu99tt.github.io/Christmas/",
        image: require("../../static/images/chrismas-min.PNG"),
        description: "",
        tags: ["html", "css", "responsive", "reactjs"],
    },
    {
        category: "Landing Page",
        dataFilter: "landing-page",
        name: "Omnifood",
        url: "https://trunghieu99tt.github.io/OmniFood/",
        image: require("../../static/images/omnifood-min.PNG"),
        description: "",
        tags: ["html", "css", "responsive", "reactjs"],
    },
    {
        category: "Landing Page",
        dataFilter: "landing-page",
        name: "Cosmetic Shop",
        url: "https://trunghieu99tt.github.io/cosmeticsShop/",
        image: require("../../static/images/cosmeticshop-min.PNG"),
        description: "",
        tags: ["html", "css", "responsive", "reactjs"],
    },

    {
        category: "Real Project",
        dataFilter: "real-project",
        name: "VgaSoft",
        url: "https://vgasoft.vn/",
        image: require("../../static/images/vgasoft-min.PNG"),
        description: "",
        tags: ["html", "css", "responsive", "reactjs"],
    },
    {
        category: "Landing Page",
        dataFilter: "landing-page",
        name: "Video Blog Template",
        url: "https://trunghieu99tt.github.io/Video-Blog/",
        image: require("../../static/images/videoblog-min.PNG"),
        description: "",
    },
    {
        category: "Landing Page",
        dataFilter: "landing-page",
        name: "Avante",
        url: "https://trunghieu99tt.github.io/avante",
        image: require("../../static/images/avante.PNG"),
        description: "",
        tags: ["html", "css", "responsive", "reactjs"],
    },

    {
        category: "Pet Project",
        dataFilter: "pet-project",
        name: "Music Player",
        url: "https://trunghieu99tt.github.io/Music-Player/",
        image: require("../../static/images/music-player-min.PNG"),
        description: "",
        tags: ["html", "css", "responsive", "reactjs"],
    },
    {
        category: "Pet Project",
        dataFilter: "pet-project",
        name: "Memory Cards",
        url: "https://trunghieu99tt.github.io/Memory-Card/",
        image: require("../../static/images/memory-card-min.PNG"),
        description: "",
        tags: ["html", "css", "responsive", "reactjs"],
    },

    {
        category: "Real Project",
        dataFilter: "real-project",
        name: "Nhà thuốc GPP",
        url: "https://nhathuocgpp.com.vn/",
        image: require("../../static/images/nhathuoc-min.PNG"),
        description: "",
        tags: ["html", "css", "responsive", "reactjs"],
    },
    {
        category: "Real Project",
        dataFilter: "real-project",
        name: "Gọi Bác Sĩ",
        url: "https://goibacsi.com.vn/",
        image: require("../../static/images/goibacsi.PNG"),
        description: "",
        tags: ["html", "css", "responsive", "reactjs"],
    },
    {
        category: "Pet Project",
        dataFilter: "pet-project",
        name: "Messenger Chat App",
        url: "https://trunghieu99tt.github.io/Messenger-Chat-App",
        image: require("../../static/images/messenger.PNG"),
        description: "",
        tags: ["html", "css", "responsive", "reactjs"],
    },
];
